---
title: "ELIXIR Lesson Title"
---

## Authors

- Erika Mustermann, The Institute of Great Science, Germany [ORCiD](https://orcid.org/1234-5678-1561-078X)
- Mario Rossi, Awesome Research University, Italy [ORCiD](https://orcid.org/1234-5678-1561-0000)

## Lesson overview

::: callout-note
## Overview

Add a short description of the training materail should be inserted here.

↩️ **Prerequisites**

To be able to follow this course, learners should have knowledge in:

1.  First requirement\
2.  Second requirement

↪️ **Learning Outcomes:**
By the end of the course, learners will be able to:

1.  First item
2.  Second item

🧑‍🤝‍🧑 **Target Audience:** Researchers, undergraduate students, postgraduate students, etc...

📈 **Level:** Beginner/Intermediate/Advanced

🔓 **License:** [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

💰 **Funding:** This project has received funding from \[name of funders\].
:::


## Contributors

- Jim Support, The Institute of Great Science, Germany [ORCiD](https://orcid.org/1234-5678-1561-078X)
- Alice Helpful, Awesome Research University, Italy [ORCiD](https://orcid.org/1234-5678-1561-0000)

## Citing this lesson

Please cite as:

.. 


## Setup

### Data setup

To run this lesson you need to install data from …

### Software setup

To run this course you need to install… continue with software installation instructions
